apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app: nginx-app
spec:
  containers:
  - name: nginx-app
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: config-volume
        mountPath: /etc/nginx/conf.d
  - name: flask-sample
    image: skilfulll1/flask-sample
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
        items:
           - key: reverseproxy.conf
             path: reverseproxy.conf

      